INSERT INTO FFF_LICENSE (LICENSE_USER, COUNTRY, PROJECT_NAME, PROJECT_CODE, MAX_SESSIONS, EXPIRY_DATE, LICENSE_KEY)
VALUES ('FIRCOSOFT','PARIS','FFF VERIFY WEB 4.5','FFFW45',500,'NEVER','4AC14CBECA02FD217EC77E3C9FACD784');
