---
project: Utilities-FMM
product: utilities
asset: database-fmm
component: SQL Server
buildDescFilenameFilterRegex: buildDesc-Windows-win32\.json$
environments:
  release:
    generateLatestTags: true
    excludedVersions:
      - 4.8.1.4
      - 4.8.1.5
      - 4.8.1.6
      - 4.10.0.0
      - 4.10.0.2
      - 4.10.0.3
      - 4.10.0.4
      - 4.10.0.5
      - 4.10.0.6
      - 4.10.1.0
      - 4.10.1.1
      - 4.10.1.2
      - 4.10.1.3
      - 4.10.1.4
      - 4.10.1.6
      - 4.10.1.7
      - 4.10.1.8
      - 4.10.2.0
      - 4.10.2.0_BETA
      - 4.10.2.1
      - 4.10.2.3
      - 4.10.2.5
      - 4.10.2.6
      - 4.10.2.7
      - 4.10.2.8
      - 4.10.2.9
      - 4.11.0.0
      - 4.11.0.1
      - 4.11.1.0
      - 4.11.1.1
      - 4.11.2.0
      - 4.11.2.1
      - 4.11.2.2
      - 4.11.3.0
      - 4.11.3.1
      - 4.11.3.2
      - 4.11.3.3
      - 4.11.3.4
      - 4.11.3.5
      - 4.11.3.6
      - 4.11.3.7
      - 4.11.3.7_BETA
      - 4.11.3.8
      - 4.11.3.8_BETA
      - 4.11.3.9_BETA
      - 4.12.0.0
      - 4.12.0.0_BETA
      - 4.12.0.0_trace
      - 4.12.1.0
      - 4.12.1.1
      - 4.12.1.2
      - 4.12.1.3
      - 4.12.1.4
      - 4.12.1.5
      - 4.12.1.6
      - 4.12.1.7
      - 4.12.2.0
      - 4.12.2.1
      - 4.12.2.2
      - 4.12.2.3
      - 4.12.2.4
      - 4.12.2.5
      - 4.12.2.7_beta
      - 4.12.3.1_BETA
    branchPrefixFilter: release
    artifacts: &artifacts
      - name: database
        filter: UTILITIES-FMM-.*.-scripts.zip$
        expand: true
        more:
          sqlScripts:
            creationScript: "SQL Server/FMM_Creation_Sql_Server.sql"
            batchScript: "SQL Server/batch-schema-sqlserver.sql"
    image: &image
      type: db
      db:
        name: sqlserver
        versions:
          - 2019
    dependencies: &dependencies
      - type: image
        name: sqlserver
        reference: jenkins-deploy.fircosoft.net/third-parties/sqlserver:2019-GA-ubuntu-16.04
    additionalTags: []
