
CREATE LOGIN CTY_DOCKER WITH
    PASSWORD    = N'hello00',
    CHECK_POLICY     = OFF,
    CHECK_EXPIRATION = OFF;
GO

CREATE USER CTY_DOCKER FOR LOGIN CTY_DOCKER 

GO 

GRANT ALL PRIVILEGES TO CTY_DOCKER
