
CREATE LOGIN ADVR_DOCKER WITH
    PASSWORD    = N'hello00',
    CHECK_POLICY     = OFF,
    CHECK_EXPIRATION = OFF;
GO

CREATE USER ADVR_DOCKER FOR LOGIN ADVR_DOCKER 

GO 

GRANT ALL PRIVILEGES TO ADVR_DOCKER
