---
version: "2.3"
services: 
  database: 
    image: jenkins-deploy.fircosoft.net/trust/database:5.2.0.0_beta-oracle12cxe
  verify: 
    image: "jenkins-deploy.fircosoft.net/trust/verify:5.2.0.0-tomcat9.0.37-openjdk11"
    environment: 
      CONTEXT_NAME: "trust"
      TRUST_DB_HOST: "database"
      TRUST_DB_PORT: "1521"
      TRUST_DB_NAME: "XE"
      TRUST_DB_USER: "trust"
      TRUST_DB_PWD: "hello00"
      TRUST_DB_DRIVER: "oracle12"
      AUTH_METHOD: "LDAP"
      LDAP_SERVER: "ldap://ldap-server:389"
      LDAP_USER: ${LDAP_USER}
      LDAP_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_USER_BASE: ${LDAP_USER_BASE}
      LDAP_USER_SEARCH: ${LDAP_USER_SEARCH}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ROLE_ATTRIBUTE_NAME: ${LDAP_ROLE_ATTRIBUTE_NAME}
      LDAP_ROLE_SEARCH_PATTERN: ${LDAP_ROLE_SEARCH_PATTERN}
    ports:
      - "8320:8080"
      - "5005:5005"
    depends_on: 
      database: 
        condition: "service_healthy"
  ldap-server:
    image: jenkins-deploy.fircosoft.net/third-parties/openldap:2.4.57
    ports:
      - 5289:389
    environment:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD}
    volumes:
      - ./ldap.bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/01-init.ldif
    command: --copy-service --loglevel debug
  ldap-client:
    image: jenkins-deploy.fircosoft.net/third-parties/ldapaccountmanager/lam:7.7
    ports:
      - 5290:80
    depends_on:
      ldap-server:
        condition: "service_started"
    environment:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_SERVER: "ldap://ldap-server:389"
      LDAP_USER: ${LDAP_USER} 
