apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: mypvc
          mountPath: /inbound
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: firco-refdata-pvclaim
