# defines possible sets of images
images:
  default:
    backend: "k3d-myregistry.localhost:12345/continuity5/backend-k8s:5.3.25.1_k8s-centos7-coreengine5.6.13.1_k8s-develop"
    filter: "k3d-myregistry.localhost:12345/filter/filter-engine-k8s:5.7.3.4"
    jdbcProxy: "k3d-myregistry.localhost:12345/continuity5/jdbcproxy:5.6.13.1_k8s-alpinejre-11.0.11_9-openjdk11-develop"
    frontend: "k3d-myregistry.localhost:12345/continuity5/verify-web:5.3.25.1-tomcat9.0.37-openjdk11-continuity5.3.25.1"
    deploymentConsole: "k3d-myregistry.localhost:12345/continuity5/deployment-console:5.3.25.1-centos7-sqlserverclient17.8.1.1-1-openjdk11-continuity5.3.25.1"
#    deploymentConsole: "k3d-myregistry.localhost:12345/continuity5/deployment-console:5.3.25.1-centos7-oracleclient19.12.0.0.0-openjdk11-continuity5.3.25.1"
    pullPolicy: Always

#############################################################################################
# Licenses
#############################################################################################
license:
  fbe: |    # Copy paste the content of your fbe.cf (backend license file)
    ARC\11\200\1\
    00001\FK_BANNER\ 7\-1\BACK-ENDS: ADRP,AMH,ARC,BAM,CMAPIS,CEMF,CRE,CWI,CLT,DBT,CMAPIM,ISO20022,MTS,MPX,PRG,PEP,REQ,SECO,SRG,TSC,XMLG,FTCLT,FTSOAP / FIRCOSOFT\
    00001\FK_SITE\ 7\-1\PARIS / FRANCE\
    00001\FK_TARGETBANK\ 7\-1\FIRCOSOFT\
    00001\FK_EXPIRATION\ 7\-1\NEVER\
    00001\FK_LANGUAGE\ 7\-1\ENGLISH\
    00001\FK_HASOFACSUBKEY\ 7\-1\ADRP,AMH,ARC,BAM,CMAPIS,CEMF,CRE,CWI,CLT,DBT,CMAPIM,ISO20022,MTS,MPX,PRG,PEP,REQ,SECO,SRG,TSC,XMLG,FTCLT,FTSOAP\
    00001\FK_MAX_PER_DAY\ 4\-1\0\
    00001\FK_KEY_M\15\4\18\V 5.3 / AIX / REAL\20\V 5.3 / LINUX / REAL\22\V 5.3 / SOLARIS / REAL\20\V 5.3 / WIN32 / REAL\\
    00001\FK_KEYS\15\4\35\0BAB8FD1-9496DDC6-715A2D68-E125EAF9\35\F09DB042-19F2D929-40BA25CE-3CEDB8D8\35\D976E2E8-368A4D57-1F087261-F867A788\35\7D7AC029-5228AFBA-A74DC926-A95A5A7D\\
  fof: | # Copy paste the content of your fof.cf (filter license file)
    ARC\11\200\1\
    00001\FOF_EXTNAME\ 7\-1\t\
    00001\FK_HASFML\ 3\-1\1\
    00001\FOF_SYCINAME\ 7\-1\fofcisy\
    00001\FK_HASOFACSUBKEY\ 7\-1\FFFFILE,FDD,FLV,FOL,FMFFILE,OFISRV,FOFRT,FOFS,FOFSAA,FOFSAE\
    00002\FK_KEYS\15\8\35\F44464AC-449D84F4-6743E056-5782EAE5\35\B3B98D9C-FB182E6F-93DFC99D-E12FFA8C\35\30135922-5F340A15-0F87FB0D-77CE9C9B\35\A8125C97-489D708A-4FC454F2-0C6D5E7D\35\3C4F3D25-49991085-1437BBE2-BE7B1DE2\35\A7ADDB74-D500E4D4-7EE26AAA-E1C58508\35\B4F28AD7-E2678062-51AEA271-0C5534AD\35\FEB320B0-E2218761-9E16703B-0E7BD496\\
    00001\FK_MAXDUMPSTAT\ 3\-1\500\
    00001\FK_PROMPT\ 7\-1\FOF:STD> \
    00001\FK_TARGETBANK\ 7\-1\FIRCOSOFT\
    00001\FOF_STATNAME\ 7\-1\fkof\
    00001\FOF_FFF_MAX\ 4\-1\0\
    00001\FK_KEY_M\15\8\18\V 5.7 / AIX / REAL\18\V 5.7 / MVS / REAL\20\V 5.7 / WIN32 / REAL\20\V 5.7 / LINUX / REAL\22\V 5.7 / SOLARIS / REAL\20\V 5.7 / OS400 / REAL\19\V 5.7 / HPUX / REAL\23\V 5.7 / GUARDIAN / REAL\\
    00001\FK_LANGUAGE\ 7\-1\ENGLISH\
    00001\FOF_DFTDB\ 7\-1\fkof\
    00001\FK_SITE\ 7\-1\PARIS / FRANCE\
    00001\FOF_MASK_LEVEL\ 5\-1\0.380000\
    00001\FK_SERVERNAME\ 7\-1\fircoof\
    00001\FOF_HAS_ALWAYS_WHOLE\ 3\-1\1\
    00001\FOF_SYNANAME\ 7\-1\fofnasy\
    00001\FK_TODAY\ 7\-1\20180927\
    00001\FK_BANNER\ 7\-1\OFAC-AGENT / FIRCOSOFT\
    00001\FOF_DFTDICO\ 7\-1\fkof\
    00001\FOF_DFTPAT\ 7\-1\fkof\
    00001\FOF_SYCONAME\ 7\-1\fofcosy\
    00001\FK_EXPIRATION\ 7\-1\NEVER\
    00001\FK_HASTRACEABILITY\ 3\-1\1\
    00001\FK_MAX_PER_DAY\ 4\-1\0\
    00001\FK_N_TODAY\ 4\-1\0\
    00001\FOF_DBNAME\ 7\-1\fofdbof\
    00001\FOF_FMF_MAX\ 4\-1\0\
  frontend:
    oracle:
      license: |
        DELETE FROM FIRCO_WKF_APPLICATION_LICENSES;
        INSERT INTO FIRCO_WKF_APPLICATION_LICENSES values ( 2, 'FIRCOSOFT', 'PARIS', 'Firco Continuity', '5.3', '100010010000001', 500, to_date('31/12/2040', 'dd/mm/yyyy' ), '8531f516afcee8b62dd2ab34056c1c60' );
        COMMIT;
    sqlserver:
      license: |
        DELETE FROM FIRCO_WKF_APPLICATION_LICENSES;
        INSERT INTO FIRCO_WKF_APPLICATION_LICENSES values ( 2, 'FIRCOSOFT', 'PARIS', 'Firco Continuity', '5.3', '100010010000001', 500, CONVERT(DATETIME, '31/12/2040', 103), '8531f516afcee8b62dd2ab34056c1c60' );
        COMMIT;
