apiVersion: v1
kind: PersistentVolume
metadata:
  name: firco-refdata-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/refdata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firco-refdata-pvclaim
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
