ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER &1 IDENTIFIED BY &2;
GRANT CONNECT, RESOURCE, CREATE ANY INDEX, CREATE ANY VIEW, UNLIMITED TABLESPACE TO &1;
ALTER USER &1 QUOTA UNLIMITED ON &3;

CREATE PROFILE UNLIMITED_PWD_PROF LIMIT PASSWORD_LIFE_TIME UNLIMITED;
ALTER USER &1 PROFILE UNLIMITED_PWD_PROF;

COMMIT;
