INSERT INTO FFF_LICENSE (LICENSE_USER, COUNTRY, PROJECT_NAME, PROJECT_CODE, MAX_SESSIONS, EXPIRY_DATE, LICENSE_KEY)
VALUES ('FIRCOSOFT','KHAZNADAR','FFF VERIFY WEB 4.7','FFFW47',0,'NEVER','8355FCBFD61DA8D6F700B9DB25BB69AE');
