{{- $fullName := include "continuity5.fullname" . -}}
{{- range $key, $value := .Values.ingresses }}
{{- if $value.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $key }}
  labels:
    {{- include "continuity5.labels" $ | nindent 4 }}
  {{- with $value.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $value.tls }}
  tls:
    {{- range $value.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $value.noHostPaths }}
    - http:
        paths:
        - path: {{ .path }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-{{ .serviceName }}
              port:
                number: {{ .servicePort }}
    {{- end }}
    {{- range $value.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-{{ .serviceName }}
                port: 
                  number: {{ .servicePort }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}