apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuity5.fullname" . }}
  labels:
    {{- include "continuity5.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "continuity5.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuity5.fullname" . }}-frontend
  labels:
    {{- include "continuity5.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "continuity5.frontend.selectorLabels" . | nindent 4 }}
