#! /bin/bash

set +x


#
# Generate all imageData and all artefacts json files for coreengine
#
generateImageDataAndArtefactsFilesForCoreEngine() {
    docker run --rm \
        -e COREENGINE_VERSION=${COREENGINE_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/coreengine-autogenerated/coreengine-centos-fircobase.mjs \
        docker/continuity5/coreengine-autogenerated/coreengine-centos-fircobase-webspheremq.mjs \
        docker/continuity5/coreengine-autogenerated/coreengine-centos-fircobase-webspheremq-oracleclient.mjs
}

#
# Generate all imageData and all artefacts json files for backend modules
#
generateImageDataAndArtefactsFilesForBackend() {
    docker run --rm \
        -e JSONUTILITIES_VERSION=${JSONUTILITIES_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/jsonutilities-autogenerated/jsonutilities.mjs
    docker run --rm \
        -e MAPPINGHTTPSTATUS_VERSION=${MAPPINGHTTPSTATUS_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/mappinghttpstatus-autogenerated/mappinghttpstatus.mjs
    docker run --rm \
        -e MAPPINGCASEMANAGERAPI_VERSION=${MAPPINGCASEMANAGERAPI_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/mappingcasemanagerapi-autogenerated/mappingcasemanagerapi.mjs
    docker run --rm \
        -e FIRCOCONTRACTMAPPER_VERSION=${FIRCOCONTRACTMAPPER_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/fircocontractmapper-autogenerated/fircoontractmapper.mjs
    docker run --rm \
        -e MAPPINGXMLUNIVERSAL_VERSION=${MAPPINGXMLUNIVERSAL_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/mappingxmluniversal-autogenerated/mappingxmluniversal.mjs

    docker run --rm \
        -e DBCLIENT_VERSION=${DBCLIENT_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/dbclient-autogenerated/upgrade-dbclient.mjs
    docker run --rm \
        -e DBTOOLS_VERSION=${DBTOOLS_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/dbtools-autogenerated/upgrade-dbtools.mjs
    docker run --rm \
        -e MULTIPLEXER_VERSION=${MULTIPLEXER_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/multiplexer-autogenerated/upgrade-multiplexer.mjs
    docker run --rm \
        -e REQUESTER_VERSION=${REQUESTER_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/requester-autogenerated/upgrade-requester.mjs
    docker run --rm \
        -e PAIRING_VERSION=${PAIRING_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/pairing-autogenerated/upgrade-pairing.mjs
    docker run --rm \
        -e STRIPPING_VERSION=${STRIPPING_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/stripping-autogenerated/upgrade-stripping.mjs
    docker run --rm \
        -e ADVANCEDREPORTING_VERSION=${ADVANCEDREPORTING_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/advancedreporting-autogenerated/upgrade-advancedreporting.mjs
    docker run --rm \
        -e DRCHECKSUMMIGRATOR_VERSION=${DRCHECKSUMMIGRATOR_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/drchecksummigrator-autogenerated/upgrade-drchecksummigrator.mjs
    docker run --rm \
        -e PREDICTIONINTEGRATOR_VERSION=${PREDICTIONINTEGRATOR_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/predictionintegrator-autogenerated/upgrade-predictionintegrator.mjs
    docker run --rm \
        -e ARCHIVING_VERSION=${ARCHIVING_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/archiving-autogenerated/upgrade-archiving.mjs
    docker run --rm \
        -e FIRCOCONTRACTMAPPER_VERSION=${FIRCOCONTRACTMAPPER_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/fircocontractmapper-autogenerated/upgrade-fircocontractmapper.mjs
    docker run --rm \
        -e JSONUTILITIES_VERSION=${JSONUTILITIES_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/jsonutilities-autogenerated/upgrade-jsonutilities.mjs
    docker run --rm \
        -e MAPPINGCASEMANAGERAPI_VERSION=${MAPPINGCASEMANAGERAPI_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/mappingcasemanagerapi-autogenerated/upgrade-mappingcasemanagerapi.mjs
    docker run --rm \
        -e MAPPINGHTTPSTATUS_VERSION=${MAPPINGHTTPSTATUS_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/mappinghttpstatus-autogenerated/upgrade-mappinghttpstatus.mjs
    docker run --rm \
        -e MAPPINGXMLUNIVERSAL_VERSION=${MAPPINGXMLUNIVERSAL_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/mappingxmluniversal-autogenerated/upgrade-mappingxmluniversal.mjs

    docker run --rm \
        -e CORENGINE_VERSIONS=${CORENGINE_VERSIONS} \
        -e PRODUCT_VERSION=${PRODUCT_VERSION} \
        -e MULTIPLEXER_VERSION=${MULTIPLEXER_VERSION} \
        -e REQUESTER_VERSION=${REQUESTER_VERSION} \
        -e DBCLIENT_VERSION=${DBCLIENT_VERSION} \
        -e DBTOOLS_VERSION=${DBTOOLS_VERSION} \
        -e PAIRING_VERSION=${PAIRING_VERSION} \
        -e STRIPPING_VERSION=${STRIPPING_VERSION} \
        -e JSONUTILITIES_VERSION=${JSONUTILITIES_VERSION} \
        -e MAPPINGHTTPSTATUS_VERSION=${MAPPINGHTTPSTATUS_VERSION} \
        -e MAPPINGCASEMANAGERAPI_VERSION=${MAPPINGCASEMANAGERAPI_VERSION} \
        -e FIRCOCONTRACTMAPPER_VERSION=${FIRCOCONTRACTMAPPER_VERSION} \
        -e MAPPINGXMLUNIVERSAL_VERSION=${MAPPINGXMLUNIVERSAL_VERSION} \
        -e ADVANCEDREPORTING_VERSION=${ADVANCEDREPORTING_VERSION} \
        -e DRCHECKSUMMIGRATOR_VERSION=${DRCHECKSUMMIGRATOR_VERSION} \
        -e PREDICTIONINTEGRATOR_VERSION=${PREDICTIONINTEGRATOR_VERSION} \
        -e ARCHIVING_VERSION=${ARCHIVING_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/cty-backend-k8s/backend-k8s.mjs

    docker run --rm \
        -e JSONUTILITIES_VERSION=${JSONUTILITIES_VERSION} \
        -e MAPPINGHTTPSTATUS_VERSION=${MAPPINGHTTPSTATUS_VERSION} \
        -e MAPPINGXMLUNIVERSAL_VERSION=${MAPPINGXMLUNIVERSAL_VERSION} \
        -e MAPPINGCASEMANAGERAPI_VERSION=${MAPPINGCASEMANAGERAPI_VERSION} \
        -e FIRCOCONTRACTMAPPER_VERSION=${FIRCOCONTRACTMAPPER_VERSION} \
        -e MULTIPLEXER_VERSION=${MULTIPLEXER_VERSION} \
        -e CORENGINE_VERSIONS=${CORENGINE_VERSIONS} \
        -e PRODUCT_VERSION=${PRODUCT_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/multiplexer-autogenerated/multiplexer-centos-fircobase-webspheremq-coreengine.mjs

    docker run --rm \
        -e JSONUTILITIES_VERSION=${JSONUTILITIES_VERSION} \
        -e MAPPINGHTTPSTATUS_VERSION=${MAPPINGHTTPSTATUS_VERSION} \
        -e MAPPINGCASEMANAGERAPI_VERSION=${MAPPINGCASEMANAGERAPI_VERSION} \
        -e FIRCOCONTRACTMAPPER_VERSION=${FIRCOCONTRACTMAPPER_VERSION} \
        -e DBCLIENT_VERSION=${DBCLIENT_VERSION} \
        -e CORENGINE_VERSIONS=${CORENGINE_VERSIONS} \
        -e PRODUCT_VERSION=${PRODUCT_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/dbclient-autogenerated/dbclient-centos-fircobase-webspheremq-oracleclient-coreengine.mjs

    docker run --rm \
        -e JSONUTILITIES_VERSION=${JSONUTILITIES_VERSION} \
        -e MAPPINGHTTPSTATUS_VERSION=${MAPPINGHTTPSTATUS_VERSION} \
        -e MAPPINGCASEMANAGERAPI_VERSION=${MAPPINGCASEMANAGERAPI_VERSION} \
        -e FIRCOCONTRACTMAPPER_VERSION=${FIRCOCONTRACTMAPPER_VERSION} \
        -e REQUESTER_VERSION=${REQUESTER_VERSION} \
        -e CORENGINE_VERSIONS=${CORENGINE_VERSIONS} \
        -e FILTER_VERSIONS=${FILTER_VERSIONS} \
        -e PRODUCT_VERSION=${PRODUCT_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/requester-autogenerated/requester-centos-fircobase-webspheremq-coreengine-filter.mjs

    docker run --rm \
        -e DBTOOLS_VERSION=${DBTOOLS_VERSION} \
        -e CORENGINE_VERSIONS=${CORENGINE_VERSIONS} \
        -e PRODUCT_VERSION=${PRODUCT_VERSION} \
        -v $(pwd):/shadoker \
        -w /shadoker \
        jenkins-deploy.fircosoft.net/shadoker/manifesto \
        --no-color \
        --generate-metadata \
        docker/continuity5/backend/dbtools-autogenerated/dbtools-centos-fircobase-webspheremq-oracleclient-coreengine.mjs
}


#
# PRODUCT_VERSION=5.3.19.5
#

CORENGINE_VERSIONS=5.6.5.9,5.6.12.0,5.6.13.1
FILTER_VERSIONS=5.8.12.0

PRODUCT_VERSION=5.3.19.5

MULTIPLEXER_VERSION=5.3.19.0
REQUESTER_VERSION=5.3.19.0
DBCLIENT_VERSION=5.3.19.0
DBTOOLS_VERSION=5.3.19.5
PAIRING_VERSION=5.3.19.0
STRIPPING_VERSION=5.3.19.0
JSONUTILITIES_VERSION=5.3.16.11
MAPPINGHTTPSTATUS_VERSION=5.3.16.12
MAPPINGCASEMANAGERAPI_VERSION=5.3.16.3
FIRCOCONTRACTMAPPER_VERSION=5.3.16.19
MAPPINGXMLUNIVERSAL_VERSION=5.3.19.0
ADVANCEDREPORTING_VERSION=5.3.19.0
DRCHECKSUMMIGRATOR_VERSION=5.3.19.0
PREDICTIONINTEGRATOR_VERSION=5.3.19.5
ARCHIVING_VERSION=5.3.19.0

generateImageDataAndArtefactsFilesForBackend


#
# PRODUCT_VERSION=5.3.23.3
#

CORENGINE_VERSIONS=5.6.5.9,5.6.12.0,5.6.13.1
FILTER_VERSIONS=5.8.12.0

PRODUCT_VERSION=5.3.23.3

MULTIPLEXER_VERSION=5.3.23.2
REQUESTER_VERSION=5.3.23.2
DBCLIENT_VERSION=5.3.23.2
DBTOOLS_VERSION=5.3.23.0
PAIRING_VERSION=5.3.23.0
STRIPPING_VERSION=5.3.23.0
JSONUTILITIES_VERSION=5.3.16.11
MAPPINGHTTPSTATUS_VERSION=5.3.16.12
MAPPINGCASEMANAGERAPI_VERSION=5.3.16.3
FIRCOCONTRACTMAPPER_VERSION=5.3.23.3
MAPPINGXMLUNIVERSAL_VERSION=5.3.23.0
ADVANCEDREPORTING_VERSION=5.3.23.0
DRCHECKSUMMIGRATOR_VERSION=5.3.23.0
PREDICTIONINTEGRATOR_VERSION=5.3.21.0
ARCHIVING_VERSION=5.3.19.0

generateImageDataAndArtefactsFilesForBackend


#
# PRODUCT_VERSION=5.3.24.1
#

CORENGINE_VERSIONS=5.6.5.9,5.6.12.0,5.6.13.1
FILTER_VERSIONS=5.8.12.0

PRODUCT_VERSION=5.3.24.1

MULTIPLEXER_VERSION=5.3.23.2
REQUESTER_VERSION=5.3.23.2
DBCLIENT_VERSION=5.3.24.0
DBTOOLS_VERSION=5.3.23.0
PAIRING_VERSION=5.3.23.0
STRIPPING_VERSION=5.3.24.0
JSONUTILITIES_VERSION=5.3.16.11
MAPPINGHTTPSTATUS_VERSION=5.3.16.12
MAPPINGCASEMANAGERAPI_VERSION=5.3.16.3
FIRCOCONTRACTMAPPER_VERSION=5.3.24.0
MAPPINGXMLUNIVERSAL_VERSION=5.3.23.0
ADVANCEDREPORTING_VERSION=5.3.24.0
DRCHECKSUMMIGRATOR_VERSION=5.3.23.0
PREDICTIONINTEGRATOR_VERSION=5.3.21.0
ARCHIVING_VERSION=5.3.24.1

generateImageDataAndArtefactsFilesForBackend


#
# PRODUCT_VERSION=5.3.25.0
#

CORENGINE_VERSIONS=5.6.5.9,5.6.12.0,5.6.13.1
FILTER_VERSIONS=5.8.12.0

PRODUCT_VERSION=5.3.25.0

MULTIPLEXER_VERSION=5.3.25.0
REQUESTER_VERSION=5.3.25.0
DBCLIENT_VERSION=5.3.25.0
DBTOOLS_VERSION=5.3.23.0
PAIRING_VERSION=5.3.23.0
STRIPPING_VERSION=5.3.25.0
JSONUTILITIES_VERSION=5.3.16.11
MAPPINGHTTPSTATUS_VERSION=5.3.16.12
MAPPINGCASEMANAGERAPI_VERSION=5.3.16.3
FIRCOCONTRACTMAPPER_VERSION=5.3.25.0
MAPPINGXMLUNIVERSAL_VERSION=5.3.25.0
ADVANCEDREPORTING_VERSION=5.3.24.0
DRCHECKSUMMIGRATOR_VERSION=5.3.23.0
PREDICTIONINTEGRATOR_VERSION=5.3.21.0
ARCHIVING_VERSION=5.3.25.0

generateImageDataAndArtefactsFilesForBackend


#
# PRODUCT_VERSION=5.3.25.1
#

CORENGINE_VERSIONS=5.6.5.9,5.6.12.0,5.6.13.1
FILTER_VERSIONS=5.8.12.0

PRODUCT_VERSION=5.3.25.1

MULTIPLEXER_VERSION=5.3.25.0
REQUESTER_VERSION=5.3.25.0
DBCLIENT_VERSION=5.3.25.0
DBTOOLS_VERSION=5.3.23.0
PAIRING_VERSION=5.3.23.0
STRIPPING_VERSION=5.3.25.0
JSONUTILITIES_VERSION=5.3.16.11
MAPPINGHTTPSTATUS_VERSION=5.3.16.12
MAPPINGCASEMANAGERAPI_VERSION=5.3.16.3
FIRCOCONTRACTMAPPER_VERSION=5.3.25.0
MAPPINGXMLUNIVERSAL_VERSION=5.3.25.1
ADVANCEDREPORTING_VERSION=5.3.24.0
DRCHECKSUMMIGRATOR_VERSION=5.3.23.0
PREDICTIONINTEGRATOR_VERSION=5.3.21.0
ARCHIVING_VERSION=5.3.25.0

generateImageDataAndArtefactsFilesForBackend


#
# PRODUCT_VERSION=5.3.26.0
#

CORENGINE_VERSIONS=5.6.5.9,5.6.12.0,5.6.13.1
FILTER_VERSIONS=5.8.12.0

PRODUCT_VERSION=5.3.26.0

MULTIPLEXER_VERSION=5.3.26.0
REQUESTER_VERSION=5.3.26.0
DBCLIENT_VERSION=5.3.26.0
DBTOOLS_VERSION=5.3.23.0
PAIRING_VERSION=5.3.23.0
STRIPPING_VERSION=5.3.25.0
JSONUTILITIES_VERSION=5.3.16.11
MAPPINGHTTPSTATUS_VERSION=5.3.16.12
MAPPINGCASEMANAGERAPI_VERSION=5.3.16.3
FIRCOCONTRACTMAPPER_VERSION=5.3.25.0
MAPPINGXMLUNIVERSAL_VERSION=5.3.25.1
ADVANCEDREPORTING_VERSION=5.3.26.0
DRCHECKSUMMIGRATOR_VERSION=5.3.23.0
PREDICTIONINTEGRATOR_VERSION=5.3.21.0
ARCHIVING_VERSION=5.3.25.0

generateImageDataAndArtefactsFilesForBackend


#
# COREENGINE_VERSION=5.6.5.9
#

COREENGINE_VERSION=5.6.5.9
generateImageDataAndArtefactsFilesForCoreEngine


#
# COREENGINE_VERSION=5.6.12.0
#

COREENGINE_VERSION=5.6.12.0
generateImageDataAndArtefactsFilesForCoreEngine


#
# COREENGINE_VERSION=5.6.13.1
#

COREENGINE_VERSION=5.6.13.1
generateImageDataAndArtefactsFilesForCoreEngine


#
# check validity of artefacts and imageData file
#

./shadoker-cli.sh package ls -w

./shadoker-cli.sh docker ls -w
